<?php

/**
 * @file
 * Defines McNeese event workflow event manage page functions.
 */

/**
 * @addtogroup mcneese_event_workflow
 * @{
 */

/**
 * Provides the event workflow event manage page.
 *
 * @param array $form
 *   The form array as defined by drupals form api.
 * @param array $form_state
 *   The form state array as defined by drupals form api
 * @param int $id
 *   The unique identifier for an event request.
 *
 * @return string
 *   The HTML output representing the page.
 */
function mcneese_event_workflow_event_manage_0_page($form, &$form_state) {

  return '';
}

/**
 * @} End of '@addtogroup mcneese_event_workflow'.
 */
